template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  - name: mvn_repo
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.myRepo.gitProvider }}     # VCS integration name
      path: {{ .Values.myRepo.path }}    # VCS Repository path
      branches:
        include: {{ .Values.myRepo.branch }}    # Specifies which branches will trigger dependent steps

  - name: mvn_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.artifactory }}

pipelines:
  - name: demo_maven
    steps:
      - name: mvn_build_step
        type: MvnBuild
        configuration:
          repositoryName: su201-mvn     # required, maven repository name on artifacctory
          sourceLocation: ./SU-201-Intro-to-JFrog-Xray/mvn-example/      # required, location of pom.xml file
          mvnCommand: clean install -ntp
          resolverSnapshotRepo: <string>      # optional
          resolverReleaseRepo:  <string>      # optional
          deployerSnapshotRepo: <string>      # optional
          deployerReleaseRepo:  <string>      # optional
          forceXrayScan:        <string>      # optional
          failOnScan:           <boolean>     # default true
          inputResources:
            - name: MvnExampleGitRepo
              trigger: false
          integrations:
            - name: Artifactory
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "11"
