resources:
  - name: git_repo 
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: GITHUB_MPATEL
      # Repository path, including org name/repo name
      path: MaharshiPatel/SwampUp2021                     # Update with your "git_user"/SwampUp2021
      branches:
        # Specifies which branches will trigger dependent steps
        include: main

  - name: npm_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory_MPATEL
      buildName:  'npm_example_pipeline'
      buildNumber: $run_number
      externalCI: Artifactory

  - name: npm_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory_MPATEL
      buildName:  'npm_example_pipeline'
      buildNumber: $run_number
      externalCI: Artifactory

  - name: npm_promoted_to_stage_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory_MPATEL
      buildName:  'npm_example_pipeline'
      buildNumber: $run_number
      externalCI: Artifactory

pipelines:
  - name: npm_example_pipeline
    configuration:
      environmentVariables:
        readOnly:
           my_env_var: '1.0.$run_number'
    steps:
      - name: npm_build_step
        type: NpmBuild
        configuration:
          repositoryName: alpha-npm-virtual                                      # required, npm repository name on artifacctory
          sourceLocation: ./SU-201-Intro-to-JFrog-Xray/npm-example/      # required, location of package.json file
          integrations:
            - name:  Artifactory_MPATEL  # required 
          inputResources:
            - name: git_repo   # required
        execution:
          onSuccess:
            - cd $res_src_resourcePath
      
      - name: test
        type: Matrix
        stepMode: Bash
        configuration:
          inputSteps:
            - name: npm_build_step
        execution:
          onExecute:
            - pushd ./setup/app
            - MODULE="$module" npm run test
            - popd
          onComplete:
            - save_tests $res_git_repo_resourcePath/sample_test.xml

      - name: npm_publish_step
        type: NpmPublish
        configuration:
          requiresApproval:
            timeoutSeconds: 43200 # if not approved in this timeframe, the step will be cancelled
            approvers:
              - maharship
          repositoryName: alpha-npm-virtual        # required, npm repository name on artifactory
          autoPublishBuildInfo: true       # optional
          forceXrayScan: true              # optional 
          failOnScan: false                 # default true
          integrations:
            - name: Artifactory_MPATEL            # required
          inputSteps:
            - name: npm_build_step         # required
          outputResources:
            - name: npm_build_info         # optional

      - name: promote_to_qa
        type: PromoteBuild
        configuration:
          requiresApproval:
              timeoutSeconds: 43200 # if not approved in this timeframe, the step will be cancelled
              approvers:
                - maharship
          targetRepository: alpha-npm-qa-local
          includeDependencies: false    # default false
          status: 'QA' 
          comment: 'Promote to QA'
          copy: true
          inputResources:
            - name: npm_build_info
          outputResources:
            - name: npm_promoted_build_info

      - name: promote_to_stage
        type: PromoteBuild
        configuration:
          requiresApproval:
              timeoutSeconds: 43200 # if not approved in this timeframe, the step will be cancelled
              approvers:
                - maharship
          targetRepository: alpha-npm-stage-local
          includeDependencies: false    # default false
          status: 'QA' 
          comment: 'Promote to QA'
          copy: true
          inputResources:
            - name: npm_promoted_build_info
          outputResources:
            - name: npm_promoted_to_stage_build_info
