resources:
  - name: git_repo 
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: GitHub
      # Repository path, including org name/repo name
      path: MaharshiPatel/SwampUp2021                     # Update with your "git_user"/SwampUp2021
      branches:
        # Specifies which branches will trigger dependent steps
        include: main

  - name: npm_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory
      buildName:  'npm_example_pipeline'
      buildNumber: $run_number
      externalCI: Artifactory
  
  - name: mvn_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory
      buildName:  'mvn_example_pipeline'
      buildNumber: $run_number
      externalCI: Artifactory

pipelines:
  - name: npm_example_pipeline
    configuration:
      environmentVariables:
        readOnly:
           my_env_var: '1.0.$run_number'
    steps:
      - name: npm_build_step
        type: NpmBuild
        configuration:
          repositoryName: swamp-npm-virtual                                      # required, npm repository name on artifacctory
          sourceLocation: ./SU-201-Intro-to-JFrog-Xray/npm-example/      # required, location of package.json file
          integrations:
            - name:  Artifactory  # required 
          inputResources:
            - name: git_repo   # required

      - name: approvalGatesStep
        type: Bash
        configuration:
          requiresApproval: true
        execution:
          onExecute:
            - echo "executing step..."
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete:
            - echo "Cleaning up some stuff"

      - name: npm_publish_step
        type: NpmPublish
        configuration:
          # for payloadType npm:
          repositoryName: swamp-npm-virtual        # required, npm repository name on artifactory
          autoPublishBuildInfo: true       # optional
          forceXrayScan: true              # optional 
          failOnScan: false                 # default true
          integrations:
            - name: Artifactory            # required
          inputSteps:
            - name: npm_build_step         # required
          outputResources:
            - name: npm_build_info         # optional

      - name: final_step
        type: Bash
        configuration:
          inputSteps:
            - name: approvalGatesStep
  
  - name: mvn_example_pipeline
    steps:
      - name: mvn_build_step
        type: MvnBuild
        configuration:
          deployerSnapshotRepo: su201-libs-snapshot
          deployerReleaseRepo:  su201-libs-release
          sourceLocation: ./SU-201-Intro-to-JFrog-Xray/maven-example/
          mvnCommand: clean install -ntp
          inputResources:
            - name: git_repo
          integrations:
            - name: Artifactory
      
      - name: publish_build
        type: PublishBuildInfo
        configuration:
          forceXrayScan: true              # optional  
          failOnScan: false                 # default true
          inputSteps:
            - name: mvn_build_step
          outputResources:
            - name: mvn_build_info
