resources:
  - name: git_repo
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: GitHub
      # Repository path, including org name/repo name
      path: MaharshiPatel/SwampUp2021
      branches:
        # Specifies which branches will trigger dependent steps
        include: pipeline

  - name: npm_buildinfo_jfp_example
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory
  
  - name: mvn_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory

pipelines:
  - name: npm_pipeline_jfp_example
    configuration:
      environmentVariables:
        readOnly:
           my_env_var: '1.0.$run_number'
    steps:
      - name: npm_build_step
        type: NpmBuild
        configuration:
          repositoryName: npm-virtual      # required, npm repository name on artifacctory
          sourceLocation: ./SU-201-Intro-to-JFrog-Xray/npm-example/      # required, location of package.json file
          integrations:
            - name:  Artifactory  # required
          inputResources:
            - name: git_repo         # required

        execution:
          onStart:
            - echo "Hello"
            - echo $run_number
            - echo $project_name
            - echo $JFROG_CLI_BUILD_NAME
            - echo $JFROG_CLI_BUILD_NUMBER
          

        #   onStart:
        #     - sed -ie 's/1.0.0/1.0.$run_number/g' package.json

      - name: npm_publish_step
        type: NpmPublish
        configuration:
          # for payloadType npm:
          repositoryName: npm-virtual        # required, npm repository name on artifactory
          autoPublishBuildInfo: true       # optional
          forceXrayScan: true
          integrations:
            - name: Artifactory      # required
          inputSteps:
            - name: npm_build_step                # required
          outputResources:
            - name: npm_buildinfo_jfp_example                 # optional
  
  - name: demo_maven
    steps:
      - name: mvn_build_step
        type: MvnBuild
        configuration:
          repositoryName: mvn-virtual
          inputResources:
            - name: git_repo
          integrations:
            - name: Artifactory
      
      - name: publish_build
        type: PublishBuildInfo
        configuration:
          forceXrayScan: false
          inputSteps:
            - name: mvn_build_step
          outputResources:
            - name: mvn_build_info