resources:
  - name: SwamupGitRepo
    type: GitRepo
    configuration:
      gitProvider: GitHub
      path: MaharshiPatel/SwampUp2021
      branches:
        include: pipeline
  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory
      buildName: npm-example
      buildNumber: 1

pipelines:
  - name: npm_example_pipeline
    configuration:
      environmentVariables:
        readOnly:
          my_app_ver: '1.0.$run_number'
    steps:
      - name: build_npm_app
        type: NpmBuild
        configuration:
          npmArgs: --no-progress --no-audit
          sourceLocation: SU-201-Intro-to-JFrog-Xray/npm-example
          repositoryName: npm
          integrations:
            - name: Artifactory
          inputResources:
            - name: SwamupGitRepo
      - name: publish_npm_app
        type: NpmPublish
        configuration:
          repositoryName: su201-npm-dev-local
          inputSteps:
            - name: build_npm_app
          integrations:
            - name: Artifactory
        execution:
          onStart:
            - export inputNpmBuildStepName="build_npm_app"